# -*- coding: utf-8 -*-
"""
/***************************************************************************
 import_KML_from_Heures
                                 A QGIS plugin
 This plugin imports a KML file produced by Heures and writes it to a geopackage, cleaning its columns.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-23
        copyright            : (C) 2025 by jabellcu
        email                : jabellcu@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'jabellcu'
__date__ = '2025-03-23'
__copyright__ = '(C) 2025 by jabellcu'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load import_KML_from_Heures class from file import_KML_from_Heures.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .import_KML_from_Heures import import_KML_from_HeuresPlugin
    return import_KML_from_HeuresPlugin()
